### ISSUE TITLE
revise costum installation

### ISSUE THREAD

**Issue by bgruening** [ngsutils/ngsutils#19]
It would be nice to get this tool via pip and a standard python library installation without the build-in virtual-env logic.

**Comment by dpryan79** [comment]
:+1: This mostly works with just `pip install git+...`, but a few directories don't get copied over that way. Doing things the normal python way would be vastly preferable and more flexible.

**Comment by bgruening** [comment]
Yes, and such things like this: https://github.com/ngsutils/ngsutils/blob/master/bin/ngsutils#L27

**Comment by dpryan79** [comment]
In fact, there's no need for any shell scripts in the package, they just make things harder to integrate.

**Comment by mbreese** [comment]
That's true that the shell scripts aren't strictly required at all. It just makes it easier to use on the command-line, but they aren't strictly necessary.

However, the virtualenv stuff is required, because it isn't always possible to add the required libraries to the global python library path.

I agree that the ./venv/bin/activate stuff is an ugly hack, but didn't want to swtich to calling venv/bin/python $action.py (which is how I'd do it now, if I stuck to python).

**Comment by bgruening** [comment]
@mbreese what do you mean by it is not possible to add the libs to the Python path? Other libraries do this as well and are useable in so many environments. Like it is today it makes it hard to use this library in any HPC env or with conda.
